language: python
python:
  - "3.6"

os:
- linux
dist: focal

install:
  - pip install sphinx==1.8.1 docutils==0.14 sphinx-rtd-theme==0.4.2 sphinxcontrib-websupport==1.1.0

before_install:
  - mkdir -p build
  - chmod 777 build
  - cd build
  - mkdir -p html
  - chmod 777 html
  - cd ..
  - touch ./build/html/.nojekyll

script:
  - make html

deploy:
  - provider: pages
    verbose: true
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./build/html/
    keep_history: true